// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotificationWebApi;

#nullable disable

namespace NotificationWebApi.Migrations
{
    [DbContext(typeof(NotifcationDbContext))]
    [Migration("20241001052815_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Notification.Models.Notification", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("is_read")
                        .HasColumnType("int");

                    b.Property<int>("post")
                        .HasColumnType("int");

                    b.Property<int>("receiver")
                        .HasColumnType("int");

                    b.Property<DateTime>("timeline")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("user")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
